config/routes.rb
 Rails.application.routes.draw do

  devise_for :users

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :trips do
    resources :bookings, except: [:show, :index]
    resources :reviews
  end
    resources :bookings, only: [:index, :show]
    get '/dashboard', to: 'trips#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :trip
  has_many :reviews

  validates :trip, presence: true

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :trip
  belongs_to :user
  validates :description, presence: true
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :users, through: :bookings
  belongs_to :user
  has_many :reviews

  has_many :bookings, dependent: :destroy
  mount_uploader :photo, PhotoUploader

  geocoded_by :destination
  after_validation :geocode, if: :will_save_change_to_destination?

  validates :name, presence: true
  validates :destination, presence: true
  validates :cost, presence: true
  validates :length, presence: true

  include PgSearch
  pg_search_scope :search_by_all,
  against: [ :name, :destination ],
  using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :trips, through: :bookings
  #make equal to true when creator equals true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!


end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_bookings, only: [ :show ]
  def index
    # raise
    @bookings = Booking.where("user_id = #{current_user[:id]}")
  end

  def show
  end

  def new
    @trip = Trip.find(params[:trip_id])
    @booking = Booking.new
    # @booking.trip = @trip
  end

  def create

    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.trip = Trip.find(params[:trip_id])
    if @booking.save
      redirect_to booking_url(@booking)
    else
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :trip_id)
  end

  def find_bookings
    @booking = Booking.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  @first_time = true

  def home
    if params[:search].present?
      @trip = Trip.where("destination ILIKE ?", "%#{params[:search][:query]}%")
    else
      @trip = Trip.all.sample(12)
   end
  end

  def search

  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @trip = Trip.find(params[:trip_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @trip = Trip.find(params["trip_id"])
    @review.trip = @trip
    @review.user = current_user
    if @review.save
      redirect_to trip_path(@trip)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:description)
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :find_trips, only: [ :show ]
  def index
    if params[:query].present?
      @trips = Trip.near(params[:query], 500)
            @markers = @trips.map do |maptrip|
      {
        lng: maptrip.longitude,
        lat: maptrip.latitude,
        infoWindow: render_to_string(partial: "/trips/map_box", locals: { trip: maptrip })
      }
      end
    elsif params[:search][:query].present?
      @trips = Trip.near(params[:search][:query], 500)
      @markers = @trips.map do |maptrip|
        {
          lng: maptrip.longitude,
          lat: maptrip.latitude,
          infoWindow: render_to_string(partial: "/trips/map_box", locals: { trip: maptrip })
        }
      end
    else
      @trips = Trip.all
      @markers = @trips.map do |maptrip|
      {
        lng: maptrip.longitude,
        lat: maptrip.latitude,
        infoWindow: render_to_string(partial: "/trips/map_box", locals: { trip: maptrip })
      }
    end

    # @maptrips = Trip.where.not(latitude: nil, longitude: nil)


    # @markers = @maptrips.map do |maptrip|
    #   {
    #     lng: maptrip.longitude,
    #     lat: maptrip.latitude,
    #     infoWindow: render_to_string(partial: "/trips/map_box", locals: { trip: maptrip })
    #   }
    end
  end

  def dashboard
    @trips = Trip.where(user: current_user)
  end

  def show
    @trip = Trip.find(params[:id])
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(trip_params)
    @trip.user = current_user
    if @trip.save
      redirect_to trip_path(@trip)
    else
      render :new
    end
  end

  private

  def trip_params
    params.require(:trip).permit(:name, :length, :cost, :destination, :photo)
  end

  def find_trips
    @trip = Trip.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container">

<h1 class="header-below-navbar">My Bookings</h1>

<div class="index-cards " >
  <% @bookings.each do |booking| %>
      <%= link_to booking_path(booking) do %>

  <div class="card-index">

    <% if booking.trip.photo.present? %>
    <%= cl_image_tag booking.trip.photo, class: "img-card" %>
    <% else %>

    <% end %>

    <div class="card-body">
      <h5 class="card-title"><%= link_to booking.trip.name, booking %></h5>
      <p class="card-text"><%= booking.trip.destination %></p>
      <% string = "#{booking.start_date} to #{booking.end_date}"%>
      <p class="card-text"><%= string %></p>
    </div>
</div>
  <% end %> <% end %>




</div>
</div>

app/views/bookings/new.html.erb
<div class="container better-form">

<h2>Booking Form</h2>

<%= simple_form_for [@booking], url: trip_bookings_url, method: :post do |f| %>
<!-- Which methods are HTTP Methods -> GET / POST / PUT / PATCH / DELETE  -->

  <div class="form-inputs">
    <%= f.input :start_date, as: :string, required: true, input_html: {class: "datepicker"} %>
    <%= f.input :end_date, as: :string, required: true, input_html: {class: "datepicker"} %>
    <%#= f.input :start_date,
                required: true,
                autofocus: true %>
    <%#= f.input :end_date,
                required: true %>
    <!-- <button type="button" class="btn btn-secondary">Write a review</button> -->

  </div>

  <div class="form-actions">
    <%= f.button :submit, "Book", name: "booking_id" , value: @booking.id, class: "btn btn-flat" %>
  </div>
<% end %>

</div>

app/views/bookings/show.html.erb
<div class="show-card-container">
  <div class="card-trip">
    <% if @booking.trip.photo.present? %>
    <%= cl_image_tag @booking.trip.photo, height: 300, width: 400, crop: :fill %>
    <% else %>
    <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg">
    <% end %>
    <div class="card-trip-right">

      <h2 class="card-trip-infos"><%= @booking.trip.name %></h2>
      <div class="booking-card-infos">
        <h4><i class="far fa-calendar-check"></i> <%= @booking.start_date %></h4>
        <h4 class="card-trip-infos"><i class="far fa-calendar-check"></i> <%= @booking.end_date %></h4>
      </div>
              <center><%= link_to "Confirm", bookings_path, class: "btn btn-flat show-btn" %></center>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="description" content="Your amazing app for booking customized trips.">
    <title>Better Bookings | Book your trip as a pro</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <% unless request.url == "http://localhost:3000/" ||  request.url == "https://airbnb-danlin2902.herokuapp.com/" %>
    <%= render 'shared/navbar' %>
    <% end %>

    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

  </body>
</html>

app/views/pages/home.html.erb
<!-- banner -->
<div class="navbar navbar-expand-sm navbar-light navbar-jacob">
  <%= link_to "/", class: "navbar-brand" do %>
    <i class="far fa-map" ></i>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

    <div class="trip-search">

    <%= form_tag trips_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a trip"
      %>
    <% end %>
    </div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "/", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Bookings", bookings_url, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Create", new_trip_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Trips", dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>




  <div class='banner slider'>
    <div class='banner slide1'></div>
    <div class='banner slide2'></div>
    <div class='banner slide3'></div>

    <div class="head-container better-form-search">
      <h1>Better Bookings</h1>
      <%= simple_form_for :search, url: trips_url, method: :get do |f| %>
      <%= f.input :query, as: :string, :placeholder => 'Where are you going?' %>
      <%= f.submit "submit ", class: "btn btn-flat" %>
      <% end %>
    </div>
  </div>
</div>

<h2 class="recs">Recommendations</h2>

<div class="index-cards " >
  <% @trip.each do |trip| %>
  <%= link_to trip_path(trip) do %>
  <div class="card-index">
    <%= cl_image_tag trip.photo, class: "img-card" %>
    <div class="card-body">
      <h5 class="card-title"><%= link_to trip.name, trip_path(trip) %></h5>
      <p class="card-text"> <%= trip.destination %></p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
  </div>
  <% end %><% end %>
</div>



<!-- footer -->


<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>
<script>
    const initUpdateNavbarOnScroll = () => {
      const navbar = document.querySelector('.navbar-jacob');
      const searchbar = document.querySelector('.trip-search');
      if (navbar) {
        console.log("hello")
        document.addEventListener('scroll', () => {
          if (window.scrollY >= window.innerHeight) {
            navbar.classList.add('navbar-lewagon-white');
            searchbar.classList.remove('trip-search');
            searchbar.classList.add('trip-search-visible');
          } else {
            navbar.classList.remove('navbar-lewagon-white');
            searchbar.classList.remove('trip-search-visible')
            searchbar.classList.add('trip-search')
          }
        });
      }
    }
    initUpdateNavbarOnScroll();
</script>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<div class="background-page-form"></div>


<div class="container better-form" style="background-color: white">
  <h2>Write a review</h2>
<%= simple_form_for ([@trip, @review]), url: trip_reviews_url, method: :post do |f| %>
  <%= f.input :description %>
  <%= f.submit "Add review", class: "btn btn-flat" %>
  <% end %>
</div>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" >
  <%= link_to "/", class: "navbar-brand" do %>
    <i class="far fa-map"></i>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

    <div class="trip-search-visible ">

    <%= form_tag trips_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a trip"
      %>
    <% end %>
    </div>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "/", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Bookings", bookings_url, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Create", new_trip_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Trips", dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/trips/_map_box.html.erb
<h3><%= trip.name %></h3>
<h6>Trip length: <%= trip.length %> days</h6>
<h6>Trip cost: €<%= trip.cost %></h6>

app/views/trips/dashboard.html.erb
<div class="container">

<h1 class="header-below-navbar">My Trips</h1>

<div class="index-cards" ">
  <% @trips.each do |trip| %>

<%= link_to trip_path(trip) do %>

  <div class="card-index">
    <% if trip.photo.present? %>
    <%= cl_image_tag trip.photo, class: "img-card" %>
    <% else %>

    <% end %>
    <div class="card-body">
    <h5 class="card-title"><%= link_to trip.name, trip %></h5>
      <p class="card-text"><%= trip.destination %></p>
    </div>

  </div>
  <% end %><% end %>
</div>

</div>





<!-- <div class="index-cards" style="display: flex; flex-wrap: wrap; flex-direction: row;"> -->

app/views/trips/index.html.erb
<div style="padding: 17px;">



<div class="trips-index-header">



<div class="trip-search">

<%= form_tag trips_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a trip"
  %>
<% end %>
</div>
   <!-- hey -->

<div class="trip-index-container">
<div class="trip-index-cards " >
  <% @trips.each do |trip| %>

      <%= link_to trip_path(trip) do %>

  <div class="trip-card-index">
    <%= cl_image_tag trip.photo, class: "img-card" %>
    <div class="card-body">
      <h5 class="card-title"><%= link_to trip.name, trip_path(trip) %></h5>
      <p class="index-card-text"> <%= trip.destination %></p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
  </div>
  <% end %><% end %>
</div>

<div
  id="map"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>
</div>

<!-- map -->

app/views/trips/new.html.erb
<div class="background-page-form"></div>


<div class="container better-form" style="background-color: white">
  <h2>Create a trip</h2>
<%= simple_form_for @trip do |f| %>
  <%= f.input :name %>
  <%= f.input :destination %>
  <%= f.input :length %>
  <%= f.input :cost %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit "Add trip", class: "btn btn-flat" %>
  <% end %>
</div>

app/views/trips/show.html.erb
  <div class="show-card-container">
    <div class="show-card-trip">
      <%= cl_image_tag @trip.photo %>

      <div class="show-card-items">
        <h2><%= @trip.name %></h2>
         <p><%= @trip.destination %></p>
        <p class="card-trip-infos">Trip length: <%= @trip.length %> days Cost: $<%= @trip.cost %>
        </p>
        <%= link_to "Book now", new_trip_booking_url(@trip), class: "btn btn-flat show-btn book-btn" %>

      </div>
    </div>
  </div>

  <div class="review-container">
    <div class="review-h3"><h3>Reviews </h3></div>
    <div class="review-view ">
      <% @trip.reviews.each do |review| %>
      <div class="review-list"><%= review.description %>
        <hr class="review-line">
      </div>
      <% end %>
    </div>

  </div>
    <div class="">
      <%= link_to "Write a review", new_trip_review_path(@trip), class: "btn btn-flat review-btn" %>
    </div>